"""Detector and risk-fusion boundary."""

from app.detection.baseline import (
    PEER_BASELINE_NAMESPACE,
    ConsensusFeature,
    PeerBaseline,
    PeerFeature,
    PeerGroupKey,
    build_peer_baseline,
    evaluate_peer_baseline,
)
from app.detection.fusion import (
    RISK_FUSION_NAMESPACE,
    RISK_WEIGHTS,
    RiskAssessment,
    RiskComponent,
    RiskLevel,
    RiskSource,
    SignalStatus,
    VerificationImpact,
    fuse_risk,
)
from app.detection.policy_engine import POLICY_FINDING_NAMESPACE, evaluate_policies
from app.detection.statistical import (
    FEATURE_NAMES,
    FEATURE_SCHEMA_VERSION,
    ISOLATION_FOREST_MODEL_VERSION,
    ISOLATION_FOREST_NAMESPACE,
    FittedIsolationForest,
    IsolationForestMetadata,
    StructuredFeatureVector,
    evaluate_isolation_forest,
    extract_structured_features,
    fit_isolation_forest,
)

__all__ = [
    "FEATURE_NAMES",
    "FEATURE_SCHEMA_VERSION",
    "ISOLATION_FOREST_MODEL_VERSION",
    "ISOLATION_FOREST_NAMESPACE",
    "PEER_BASELINE_NAMESPACE",
    "POLICY_FINDING_NAMESPACE",
    "RISK_FUSION_NAMESPACE",
    "RISK_WEIGHTS",
    "ConsensusFeature",
    "FittedIsolationForest",
    "IsolationForestMetadata",
    "PeerBaseline",
    "PeerFeature",
    "PeerGroupKey",
    "RiskAssessment",
    "RiskComponent",
    "RiskLevel",
    "RiskSource",
    "SignalStatus",
    "StructuredFeatureVector",
    "VerificationImpact",
    "build_peer_baseline",
    "evaluate_isolation_forest",
    "evaluate_peer_baseline",
    "evaluate_policies",
    "extract_structured_features",
    "fit_isolation_forest",
    "fuse_risk",
]
