"""Domain contracts shared by API, parsers, and detectors."""

from app.domain.models import (
    AclConfig,
    AclRule,
    BgpConfig,
    BgpNeighborConfig,
    CanonicalConfig,
    ConfigSource,
    DeviceInfo,
    Evidence,
    Finding,
    InterfaceAddress,
    InterfaceConfig,
    ManagementConfig,
    OspfInterfaceConfig,
    OspfNetworkConfig,
    OspfProcessConfig,
    PrefixListConfig,
    PrefixListRule,
    Severity,
    SourceLocation,
    StaticRouteConfig,
    UnparsedFragment,
    Vendor,
    VlanConfig,
    VlanReference,
    VlanSet,
)

__all__ = [
    "AclConfig",
    "AclRule",
    "BgpConfig",
    "BgpNeighborConfig",
    "CanonicalConfig",
    "ConfigSource",
    "DeviceInfo",
    "Evidence",
    "Finding",
    "InterfaceAddress",
    "InterfaceConfig",
    "ManagementConfig",
    "OspfInterfaceConfig",
    "OspfNetworkConfig",
    "OspfProcessConfig",
    "PrefixListConfig",
    "PrefixListRule",
    "Severity",
    "SourceLocation",
    "StaticRouteConfig",
    "UnparsedFragment",
    "Vendor",
    "VlanConfig",
    "VlanReference",
    "VlanSet",
]
