set system host-name juniper-access-01
set system services telnet
set system ntp server 192.0.2.11
set system syslog host 192.0.2.21 any warning
set snmp community REDACTED authorization read-only
set system time-zone UTC
