set system host-name juniper-access-01
set system services telnet
set system ntp server 192.0.2.11
set system syslog host 192.0.2.21 any warning
set snmp community REDACTED authorization read-only
set vlans USERS vlan-id 10
set interfaces ge-0/0/1 description "User access"
set interfaces ge-0/0/1 disable
set interfaces ge-0/0/1 unit 0 family inet address 192.0.2.9/30
set interfaces ge-0/0/2 description "Office access"
set interfaces ge-0/0/2 unit 0 family ethernet-switching interface-mode access
set interfaces ge-0/0/2 unit 0 family ethernet-switching vlan members USERS
set system time-zone UTC
set firewall family inet filter MGMT-IN term ALLOW-SSH from source-address 192.0.2.0/24
set firewall family inet filter MGMT-IN term ALLOW-SSH from protocol tcp
set firewall family inet filter MGMT-IN term ALLOW-SSH from destination-port ssh
set firewall family inet filter MGMT-IN term ALLOW-SSH then accept
set firewall family inet filter MGMT-IN term DENY-REST then discard
set policy-options prefix-list TRUSTED 192.0.2.0/24
set routing-options static route 0.0.0.0/0 next-hop 192.0.2.10
set routing-options static route 0.0.0.0/0 preference 15
set routing-options static route 203.0.113.0/24 discard
