set system host-name juniper-access-01
set system services telnet
set system ntp server 192.0.2.11
set system syslog host 192.0.2.21 any warning
set snmp community REDACTED authorization read-only
set interfaces ge-0/0/1 description "User access"
set interfaces ge-0/0/1 disable
set interfaces ge-0/0/1 unit 0 family inet address 192.0.2.9/30
set system time-zone UTC
