system {
    host-name juniper-edge-01;
    services {
        ssh;
    }
    authentication-order [ radius password ];
    ntp {
        server 192.0.2.10;
    }
    syslog {
        host 192.0.2.20 {
            any notice;
        }
    }
}
snmp {
    v3 {
    }
}
